name: video-streaming-app
services:
  streaming-server:
    build: .
    image: streaming-server-cpp:latest
    container_name: streaming-server
    ports:
      - "9000:9000"
    volumes:
      - C:\Users\HP\Desktop\HostedProjects\VideoStreaming_C++_Server\video:/app/video:ro
