name: CI/CD Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Update and Deploy Server
        run: |
          cd /home/subaru/projects/StreamingServer/Streaming-Server-in-Cpp
          git fetch origin
          git reset --hard origin/main
          sg docker -c "docker-compose up -d --build"
          sg docker -c "docker image prune -f"
